// Code generated by MockGen. DO NOT EDIT.
// Source: app/log/log.go
//
// Generated by this command:
//
//	mockgen -source=app/log/log.go -destination=app/log/mock/log.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLog is a mock of Log interface.
type MockLog struct {
	ctrl     *gomock.Controller
	recorder *MockLogMockRecorder
	isgomock struct{}
}

// MockLogMockRecorder is the mock recorder for MockLog.
type MockLogMockRecorder struct {
	mock *MockLog
}

// NewMockLog creates a new mock instance.
func NewMockLog(ctrl *gomock.Controller) *MockLog {
	mock := &MockLog{ctrl: ctrl}
	mock.recorder = &MockLogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLog) EXPECT() *MockLogMockRecorder {
	return m.recorder
}

// Error mocks base method.
func (m *MockLog) Error(message string, data any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", message, data)
}

// Error indicates an expected call of Error.
func (mr *MockLogMockRecorder) Error(message, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLog)(nil).Error), message, data)
}

// Info mocks base method.
func (m *MockLog) Info(message string, data any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", message, data)
}

// Info indicates an expected call of Info.
func (mr *MockLogMockRecorder) Info(message, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLog)(nil).Info), message, data)
}

// Warning mocks base method.
func (m *MockLog) Warning(message string, data any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warning", message, data)
}

// Warning indicates an expected call of Warning.
func (mr *MockLogMockRecorder) Warning(message, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warning", reflect.TypeOf((*MockLog)(nil).Warning), message, data)
}
